export type AgentApplyItem = {
  // generate type according to above json
  createBy: string;
  createTime: string;
  updateBy: string | null;
  updateTime: string | null;
  remark: string | null;
  params: Record<string, unknown>;
  id: string;
  lastName: string;
  name: string;
  mzone: string;
  mobile: string;
  email: string;
  pwd: string;
  salt: string;
  certiricateType: string | null;
  certiricateNo: string | null;
  certiricateFront: string | null;
  certiricateBack: string | null;
  havingAgent: number;
  verifyStatus: number;
  applySource: number;
  inviter: string;
  spreadLinkCodeId: string;
  userId: string | null;
  showId: string | null;
  verifyTime: string | null;
  verifyUser: string | null;
  inviterName: string | null;
  verifyStep: number;
  verifyUserName: string | null;
  language: string;
  identityInfo: string;
  defaultRole: string;
  columns: string | null;
  userName: string;
  vuserName: string;
};

export type AgentApplyListRes = {
  code: number;
  msg: string;
  rows: AgentApplyItem[];
  total: string;
};

export type AgentApplyListParams = {
  pageNum?: number;
  pageSize?: number;
  orderByColumn?: string;
  isAsc?: string;
  name?: string;
  mobile?: string | number;
  email?: string;
  verifyStatus?: number | string;
  applySource?: number | string;
  verifyUserName?: string;
  params: {
    beginTime?: string;
    endTime?: string;
  };
};

export type RebateCommissionItem = {
  // generate type according to above json
  createBy: string | null;
  createTime: string | null;
  updateBy: string | null;
  updateTime: string | null;
  remark: string | null;
  params: Record<string, unknown>;
  id: string;
  userId: string;
  orderId: string;
  mtOrder: string;
  serverName: string;
  serverId: string;
  serverType: string;
  taderType: string | null;
  lastName: string;
  name: string;
  showId: string;
  rebateTotalAmt: string;
  rebateFixedAmt: string;
  rebatePointsAmt: string;
  rebateTime: string;
  rebateStatus: string;
  trderAccount: string;
  trderCount: string;
  amtUnit: string;
  verifyId: string | null;
  traderTime: string;
  traderTimeStr: string;
  verifyTime: string | null;
  rebateTraderId: string;
  rebateCommissionId: string;
  rebateType: string;
  rebateTraderRuleId: string;
  commissionBase: string;
  accountGroupList: string | null;
  model: number;
  rebateAccountType: string | null;
  rebateAccount: string | null;
  settleStyle: number;
  ticket: string;
  deal: string;
  login: string;
  symbol: string;
  volume: string;
  userName: string;
  rebateUser: string;
  totalAmtText: string;
  currency: string;
  inMoneyAmt: string;
  percentage: string;
  commission: string;
  rebateTraderName: string;
  verifyName: string;
  rebateAccountName: string | null;
  verifyStep: number;
  verifyUserName: string | null;
  orderComment: string;
};

export type RebateCommissionListRes = {
  code: number;
  msg: string;
  rows: RebateCommissionItem[];
  total: string;
};

export type RebateCommissionListParams = {
  pageNum?: number;
  pageSize?: number;
  orderByColumn?: string;
  isAsc?: string;
  serverId?: string;
  rebateType?: string | number;
  serverGroup?: string;
  serverGroupList?: string;
  mtOrder?: number | string;
  trderAccount?: string;
  rebateStatus?: number | string;
  id?: string | null;
  rebateTraderId?: string | null;
  verifyUserName?: string;
  accountGroupList?: string;
  conditionName?: string;
  params: {
    startTraderTime?: string;
    endTraderTime?: string;
    beginTime?: string;
    endTime?: string;
  };
};

export type RebateCommissionRuleItem = {
  createBy: string | null;
  createTime: string;
  updateBy: string | null;
  updateTime: string;
  remark: string | null;
  params: Record<string, unknown>;
  id: string;
  userId: string | null;
  accountId: string | null;
  serialNumber: string;
  ruleName: string;
  hasUsed: string;
  rebateGroupType: string | null;
  mtGroup: string | null;
  settleUnit: string | null;
  highestRebateLevel: string;
  relatedAccountCount: string | null;
  relatedRebateTemplateCount: string | null;
  serverType: string;
  serverName: string | null;
  serverId: string;
  groupTypeId: string | null;
  rebateType: string;
  accountGroups: string | null;
  model: number;
  settleType: string | null;
  commissionSettlementTiming: number;
  suitType: number;
  settleValue: number;
  crmRebateLevels: string | null;
  ruleAndModel: string;
  traderServers: string | null;
  traderLanguages: string | null;
};
